-- 1) Tipos de nómina
CREATE TABLE pay_payroll_types (
  payroll_type_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code            VARCHAR2(20) UNIQUE NOT NULL,  -- MENSUAL, QUINCENAL
  description     VARCHAR2(100) NOT NULL
);

-- 2) Conceptos
CREATE TABLE pay_concepts (
  concept_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code            VARCHAR2(30) UNIQUE NOT NULL,   -- HED, HEN, VAC, SAL_BASE
  name            VARCHAR2(100) NOT NULL,
  concept_type    VARCHAR2(10)  NOT NULL CHECK (concept_type IN ('DEVENGO','DEDUCCION')),
  calc_method     VARCHAR2(15)  NOT NULL CHECK (calc_method IN ('FIJO','PORCENTAJE','POR_HORA','POR_DIA')),
  default_rate    NUMBER(12,4),                   -- % o tarifa por hora/día
  is_active       CHAR(1) DEFAULT 'Y' CHECK (is_active IN ('Y','N'))
);

-- 3) Periodos
CREATE TABLE pay_periods (
  period_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  payroll_type_id NUMBER NOT NULL REFERENCES pay_payroll_types(payroll_type_id),
  period_code  VARCHAR2(20) NOT NULL,             -- 2026-02, 2026Q1-01, etc.
  date_start   DATE NOT NULL,
  date_end     DATE NOT NULL,
  status       VARCHAR2(10) DEFAULT 'ABIERTO' CHECK (status IN ('ABIERTO','CERRADO')),
  CONSTRAINT uk_pay_period UNIQUE (payroll_type_id, period_code),
  CONSTRAINT ck_pay_period_dates CHECK (date_end >= date_start)
);

-- 4) Contratos (condiciones por empleado)
CREATE TABLE pay_emp_contracts (
  contract_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id     NUMBER NOT NULL REFERENCES employees(employee_id),
  payroll_type_id NUMBER NOT NULL REFERENCES pay_payroll_types(payroll_type_id),
  base_salary     NUMBER(12,2) NOT NULL,
  hours_per_month NUMBER(6,2) DEFAULT 240,        -- para calcular valor hora
  start_date      DATE NOT NULL,
  end_date        DATE,
  status          VARCHAR2(10) DEFAULT 'ACTIVO' CHECK (status IN ('ACTIVO','INACTIVO')),
  CONSTRAINT ck_contract_dates CHECK (end_date IS NULL OR end_date >= start_date)
);

-- 5) Registro de horas (horas extra/recargos)
CREATE TABLE pay_time_entries (
  time_entry_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id   NUMBER NOT NULL REFERENCES employees(employee_id),
  work_date     DATE   NOT NULL,
  concept_id    NUMBER NOT NULL REFERENCES pay_concepts(concept_id), -- ej HED/HEN/DOM
  hours_qty     NUMBER(6,2) NOT NULL CHECK (hours_qty > 0),
  notes         VARCHAR2(200)
);

-- 6) Vacaciones / licencias
CREATE TABLE pay_leave_requests (
  leave_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id  NUMBER NOT NULL REFERENCES employees(employee_id),
  leave_type   VARCHAR2(15) NOT NULL CHECK (leave_type IN ('VACACIONES','INCAPACIDAD','LICENCIA')),
  date_start   DATE NOT NULL,
  date_end     DATE NOT NULL,
  days_qty     NUMBER(6,2),
  status       VARCHAR2(12) DEFAULT 'APROBADA' CHECK (status IN ('SOLICITADA','APROBADA','RECHAZADA')),
  CONSTRAINT ck_leave_dates CHECK (date_end >= date_start)
);

-- 7) Novedades (bonos, descuentos, préstamos, etc.)
CREATE TABLE pay_emp_events (
  event_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id  NUMBER NOT NULL REFERENCES employees(employee_id),
  period_id    NUMBER NOT NULL REFERENCES pay_periods(period_id),
  concept_id   NUMBER NOT NULL REFERENCES pay_concepts(concept_id),
  qty          NUMBER(10,2) DEFAULT 1,             -- unidades/días/horas si aplica
  amount       NUMBER(12,2),                       -- monto directo si aplica
  rate         NUMBER(12,4),                       -- % o tarifa si aplica
  notes        VARCHAR2(200)
);

-- 8) Cabecera de nómina (desprendible)
CREATE TABLE pay_payslips (
  payslip_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  period_id    NUMBER NOT NULL REFERENCES pay_periods(period_id),
  employee_id  NUMBER NOT NULL REFERENCES employees(employee_id),
  calc_date    DATE DEFAULT SYSDATE,
  gross_total  NUMBER(12,2) DEFAULT 0,
  ded_total    NUMBER(12,2) DEFAULT 0,
  net_total    NUMBER(12,2) DEFAULT 0,
  status       VARCHAR2(12) DEFAULT 'CALCULADO' CHECK (status IN ('CALCULADO','APROBADO','PAGADO')),
  CONSTRAINT uk_payslip UNIQUE (period_id, employee_id)
);

-- 9) Detalle por concepto
CREATE TABLE pay_payslip_lines (
  line_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  payslip_id   NUMBER NOT NULL REFERENCES pay_payslips(payslip_id) ON DELETE CASCADE,
  concept_id   NUMBER NOT NULL REFERENCES pay_concepts(concept_id),
  qty          NUMBER(10,2),
  unit_value   NUMBER(12,4),
  line_total   NUMBER(12,2) NOT NULL,
  CONSTRAINT ck_line_total CHECK (line_total <> 0)
);
